Small Library app to test Javascript OOP features
emasdev/Library pull request #2
Opened 2021-01-30 14:25 UTC by MkrtichSargsyan

In this project, we build a small Library app to show and add books.

1. Bookmark your books as favorite and set if you have already read it or not. There are options to filter the books in the ones you compleated or the ones that not.​

2. Every move is saved in the local storage of your browser.

2021-01-30 14:38 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 
- Good work structuring your code properly.

## However, there are some changes required 👀 🧰 🔨 🔧 
- When I try to delete a single book, it does initially disappear from the page. But if I click on any of the tabs (All books, Not finished yet books, Finished books), the book appears again. Please fix this.
- Your Live Demo link is broken. Please fix it.

**[ OPTIONAL ]**
- I'm able to add books with blank titles. Please validate all input fields before adding new books.
- You may add a data persistence method such as Firebase or localStorage.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-01 17:05 UTC, emasdev commented
- Issue with removed books is already fixed

- "You may add a data persistence method such as Firebase or localStorage." 
We are using local storage to persist the data in the library.js file

2021-02-01 17:45 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @MkrtichSargsyan and @emasdev :wave: 

### Good job fixing almost all of the issues pointed by the last TSE. There's still one bug we need to fix, please check my comment on your code and the request below:

- [ ] Your Pull Request is currently not checking for linter errors, please fix this issue.

Kindly make the requested changes and submit them for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-02-01 17:45 UTC, MuriloRoque commented on scripts/helper.js
> +    });
- [ ] The bug still persists when I click this button. When I try to remove a book using it, it disappears, but when I refresh the page or click somewhere else, it's still there. Also, I checked the `localStorage` using the console and it doesn't change when I click this button. Please try debugging this and fix this issue.

2021-02-01 19:13 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!


- [ ] `OPTIONAL` I can still fill in blank inputs, the only one that wouldn't be accepted if blank is the "cover" field, please fix it for all of them, also, it would be better if you can add an error message so a user would know what's the issue.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-02 11:06 UTC, merged